### ISSUE TITLE
Data Scraping

### ISSUE THREAD

**Issue by nod0n** [CryptoFraudDetection/main#20]
- [ ] Get price time series
- [ ] Define start and end of time window for each coin
- [ ] Gather social media data of time window for each coin
	- [x] Reddit as website (@FloBaumgartner @nod0n)
	- [x] X as website (@can020202) #28 
	- [x] Google Results (@gabrieltorresgamez) #24 
	- [x] [Comparitech Rug Pulls List](https://www.comparitech.com/crypto/cryptocurrency-scams/) (@gabrieltorresgamez) #31 
	- [ ] Google Trends (@nod0n @FloBaumgartner)
